// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dsavfcfrvgygzpyasbez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzYXZmY2Zydmd5Z3pweWFzYmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzg3NTIsImV4cCI6MjA3MTcxNDc1Mn0._8oUhRBct8706RVs_vTIRJNhzTBwEpAErpclak2SFfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});